#!/usr/bin/env python3
"""Render page.md to index.html with plain Python-Markdown (ROADMAP chunk 2.4).

The bare extension, no MkDocs: this is what any other Python-Markdown host gets. The viewer
is loaded from the Vite build through the e2e static server (``node scripts/serve.mjs``
serves the repository root), so ``npm run build`` must have run. Requires the package
(``pip install -e ".[yaml]"`` from the repository root, then ``python scripts/sync_viewer.py``
for the options schema copy); the YAML extra gives the YAML example a search fallback too.
Run from anywhere::

    python viewer/test/e2e/markdown/render.py
"""

from __future__ import annotations

import os
from pathlib import Path

import markdown

from asyncapi_viewer.extension import AsyncAPIViewerExtension

HERE = Path(__file__).resolve().parent


def resolve_file(src: str) -> "str | None":
    """src is relative to the page, and the page is served from its own directory."""
    path = HERE / src
    return str(path) if path.is_file() else None


def main() -> None:
    warnings: list[str] = []
    body = markdown.markdown(
        (HERE / "page.md").read_text(encoding="utf-8"),
        extensions=[
            AsyncAPIViewerExtension(
                viewer_js="/viewer/dist/asyncapi-viewer.js",
                viewer_js_integrity="",
                viewer_theme="/viewer/theme/asyncapi-theme.css",
                viewer_theme_integrity="",
                file_resolver=resolve_file,
                warn=warnings.append,
            ),
            "fenced_code",
        ],
    )
    if warnings:
        raise SystemExit("unexpected warnings:\n" + "\n".join(warnings))
    page = (
        "<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n"
        "<title>asyncapi-viewer Python-Markdown page</title>\n"
        "<!-- generated by render.py from page.md; not committed -->\n</head>\n<body>\n"
        f"{body}\n</body>\n</html>\n"
    )
    out = HERE / "index.html"
    out.write_text(page, encoding="utf-8")
    print(f"wrote {os.path.relpath(out)}")


if __name__ == "__main__":
    main()
